= Mein Arbeitstagebuch zur Reflexion
:page-pdf-download: true
:icons: font
:table-grid: none
:table-frame: ends
:table-stripes: even

Bearbeitet durch: _Samuele Ancona_

E-Mail: _samuele.ancona@students.fhnw.ch_

'''
== Do's
NOTE: Jeden Abend kurze Notizen schreiben, welche man später noch ausformulieren kann. Commit&Push every day.

== Dont's
IMPORTANT: KI die Reflexion schreiben lassen.

'''

=== Montag, 10.08.2026

==== Was habe ich heute gemacht?
CasualTime gelöst — zuerst simpel mit if/else, dann eine separate Methode für das Stundenformat extrahiert, um den Code übersichtlicher zu gestalten.

==== Spass gemacht hat?
Das Refactoring der `hourFormat`-Methode.

==== Mühsam war?
Die erste Lösung mit vielen verschachtelten if/else-Verzweigungen.

==== Was ich noch Anschauen will

'''

=== Was habe ich heute gemacht?
* erstelle pro Tag einen Abschnitt

=== Spass gemacht hat?

=== Mühsam war?

=== Was ich noch Anschauen will




'''
Hier nochmals die Links zu den Aufgaben, so kann man die Reflexion gleich mit den Aufgaben verknüpfen:

link:./aufgaben/src/casualtime/index.adoc[casualtime - Casual Time]

link:./aufgaben/src/wordwrap/index.adoc[wordwrap - Automatischer Zeilenumbruch]

link:./aufgaben/src/morse/index.adoc[morse - Morsecode]

link:./aufgaben/src/datetime/index.adoc[datetime - Datumsangaben und Uhrzeiten formatieren]

link:./aufgaben/src/calc/index.adoc[calc - Calculator: Code aufräumen und debuggen]

und die Refactoring Aufgaben:
link:./refactoring/src/index.adoc[Refactorings]

